<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.bitworksmc</groupId>
    <artifactId>HeadDB</artifactId>
    <version>6.0.2</version>
    <packaging>pom</packaging>

    <name>HeadDB</name>
    <description>Head Database</description>

    <modules>
        <module>headdb-api</module>
        <module>headdb-core</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <adventure.version>5.2.0</adventure.version>
        <annotations.version>26.1.0</annotations.version>
        <paper.minecraft.version>26.2</paper.minecraft.version>
        <paper.version>${paper.minecraft.version}.build.112-stable</paper.version>
        <sqlite.version>3.53.2.1</sqlite.version>
    </properties>

</project>
